### ISSUE TITLE
Malli invalid-schema error in scicloj\metamorph\ml.clj

### ISSUE THREAD

**Issue by swapneils** [scicloj/metamorph.ml#4]
When trying to import metamorph.ml and use it with scicloj.ml, I run into a malli spec error. Removing malli 0.7.5 from my project.clj dependencies results in the program working fine.

Error message:
`clojure-main.core> (require '[scicloj.ml.core :as ml] '[scicloj.ml.metamorph :as mm] '[scicloj.ml.dataset :as ds])`
`Syntax error (ExceptionInfo) compiling at (scicloj\metamorph\ml.clj:698:1).`
`:malli.core/invalid-schema {:schema :pipe-fns-clj-file}`

The error occurs at line 698 in [this file](https://github.com/scicloj/metamorph.ml/blob/main/src/scicloj/metamorph/ml.clj), but I suspect the schema causing this issue is actually at line 341, the only occurrence of ":pipe-fns-clj-file" inside a malli spec in that file.

Is there some incompatibility between malli 0.6.2 and 0.7.5 schema formats for maps? 
Or was it just a typo that the map object was written as `[:map [:ns any? :pipe-fns-clj-file string?]]` instead of `[:map [:ns any?] [:pipe-fns-clj-file string?]]`, and removing malli is simply preventing evaluation of the incorrect schema?

(note: metamorph is being imported manually in this project, as per [a comment on issue 5 in the scicloj.ml repository](https://github.com/scicloj/scicloj.ml/issues/5#issuecomment-1009051169))

**Comment by behrica** [comment]
fixed by #5
